### ISSUE TITLE
GPU and Memory Requirements for Running CAGE #1

### ISSUE THREAD

**Issue by yanrihong** [cage-policy/CAGE#1]
Hello,

Thank you for your work on CAGE! It is a very solid project. I am especially interested in the "Causal Observation Perceiver" module.

also, I have a very basic question:

**Can I  train the model with RTX4090 * 1 ?**

Thanks!

**Comment by Xiashangning** [comment]
Thanks for your interest in our project!

> Can I train the model with RTX4090 * 1 ?

Sure, from our experience, CAGE takes about 62GB with a batch size of 16, 34GB with a batch size of 8. If you want to train on a single 4090, you would probably want to set `batch_size=4` with `gradient_accumulation_steps=16` in order to have **an effective batch size >= 64**. Or you might use `DINOv2-big/small` instead to reduce the memory usage.
