### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by yanrihong** [cage-policy/CAGE#4]
Hi,
Thanks for your solid works,
For the datasets part, I notice that:
all camera dir has **gripper info** and **gripper command**, are they the same ?

 
![image](https://github.com/user-attachments/assets/d44b87f4-7057-4ff3-b117-42f764af0041)

**Comment by Galaxies99** [comment]
- `gripper_info` records the gripper's real-time information. We only use the first value (the width of the gripper) as proprioception inputs. 
- `gripper_command` records the last command sent to the gripper during the teleoperation process. We only use the first value (the width of the gripper) as ground-truth actions.

Here is an example to help understand their differences. Suppose I want to teleoperate the robot (with a gripper) to grasp a rigid object like a block. Humans will send grasping signals (like closing the gripper) through the teleoperation interface to the robot (with the gripper). This information (closing the gripper, gripper target width = 0) will be sent to the robot, and the robot will execute grasping the block (gripper will close to target width = 0). Since the target width (0) is unreachable when grasping a block, the gripper will grasp the block firmly. As a result, when accessing gripper information at this time, we will find that the gripper width will correspond to the block's width, not 0. Ideally, we want to make the policy learn the grasping behavior by setting the gripper width to 0 (i.e., closing the gripper to grasp the object firmly), instead of setting the gripper width to the width of the block. That's why we use `gripper_command` as action labels, and `gripper_info` as observation inputs.

**Comment by yanrihong** [comment]
Thanks for your kindly reply! i mean each camera's gripper_info the same? :)

**Comment by Galaxies99** [comment]
> Thanks for your kindly reply! i mean each camera's gripper_info the same? :)

No, they are not the same. We will align all the data to the main global camera's timestamps by selecting the nearest timestamp in each camera.

**Comment by yanrihong** [comment]
oh， I get you，
But I still have some questions,

When I save the robot obs data,

for each timestamp saving operation, i save both two camera's RGB and the gripper command, info and tcp at the same time.

which means I only have **one group** of (gripper command, info and tcp),

then i organize the collection as the same architecture as yours.

i wonder if this will influence the robot performance ?

**Comment by Galaxies99** [comment]
> oh， I get you， But I still have some questions,
> 
> When I save the robot obs data,
> 
> for each timestamp saving operation, i save both two camera's RGB and the gripper command, info and tcp at the same time.
> 
> which means I only have **one group** of (gripper command, info and tcp),
> 
> then i organize the collection as the same architecture as yours.
> 
> i wonder if this will influence the robot performance ?

Generally, it will not affect the policy performance, as long as using the same protocols (a group of two cameras, gripper info/command, tcp) to get observations during inference (deployment) and training. You might need to change `utils/dataset.py` to accommodate your dataset.

**Comment by Galaxies99** [comment]
> > Thanks for your kindly reply! i mean each camera's gripper_info the same? :)
> 
> No, they are not the same. We will align all the data to the main global camera's timestamps by selecting the nearest timestamp in each camera.

In our settings, we are using the (color, gripper_command, gripper_info, tcp) in the main camera folder, while only using "color" in the inhand camera folder. Therefore, proprioception observations in the inhand camera folder are unused.

**Comment by yanrihong** [comment]
Thanks for your kindly reply! 
I will try it !
